server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: envyguard-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/envyguard_db
    username: postgres  # Cambia esto si no es 'postgres'
    password: Qwe.123*  # La que usas para psql
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # RabbitMQ (si lo vas a usar)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  security:
    jwt:
      secret: EnvyGuardSecretKeyForJWT256BitsSecurity2024ChangeThisInProduction
      expiration: 86400000 # 24 horas en milisegundos
  
  admin:
    email: "admin@envyguard.com"
    password: "Admin123!"
    firstName: "EnvyGuard"
    lastName: "Administrator"

logging:
  level:
    com.envyguard: DEBUG
    org.springframework.security: DEBUG